### ISSUE TITLE
Listepunkter i meldinger

### ISSUE THREAD

**Issue by maccyber** [telemark/portalen-forside#424]
Listepunkter i meldinger havner for nære meldingsboksen.

![meld il](https://cloud.githubusercontent.com/assets/701351/19111759/889eb25c-8b01-11e6-85be-84d3f6957447.png)

Fikses med noe lignende:
```css
ul { list-style-position: inside }
```
