### ISSUE TITLE
Menyknapper i meldinger

### ISSUE THREAD

**Issue by maccyber** [telemark/portalen-forside#425]
Menyknapper i meldinger er i horisontal senter.
Skal være oppe til høyre.
![meld buttons](https://cloud.githubusercontent.com/assets/701351/19112301/6448c50c-8b04-11e6-8408-060db63eb8e3.png)

Kan fikses med noe lignende:

```css
span {
    position: absolute;
    top: 0;
    right: 0;
}
```
