### ISSUE TITLE
Tekst i meldinger

### ISSUE THREAD

**Issue by maccyber** [telemark/portalen-forside#426]
Tekst i meldinger kuttes ikke.
Gjelder sannsynligvis bare IE.

![v0n4qlh4](https://cloud.githubusercontent.com/assets/701351/19112853/68fd62f8-8b07-11e6-9061-286093137303.jpeg)

Fikses med noe lignende:
```css
p {
  word-wrap: break-word;
  word-break: break-all;
}
```
